import type { ComponentDefinition } from '../types/prototype';

export const COMPONENT_REGISTRY: ComponentDefinition[] = [
  {
    type: 'u6u-btn',
    label: '按鈕',
    icon: '🔵',
    category: 'input',
    defaultProps: { label: '按鈕', color: '#3b82f6', tooltip: '', disabled: '' },
    propsSchema: [
      { key: 'label', label: '顯示文字', type: 'text', placeholder: '按鈕' },
      { key: 'color', label: '主題色', type: 'color' },
      { key: 'tooltip', label: '滑鼠提示', type: 'text' },
    ],
    supportedEvents: [{ event: 'ON_CLICK', description: '點擊時觸發' }],
  },
  {
    type: 'u6u-text-input',
    label: '單行輸入',
    icon: '📝',
    category: 'input',
    defaultProps: { label: '', name: '', placeholder: '輸入文字…', value: '' },
    propsSchema: [
      { key: 'label', label: '欄位標籤', type: 'text' },
      { key: 'name', label: '欄位名稱', type: 'text', description: 'u6u-card 收集值時使用' },
      { key: 'placeholder', label: '提示文字', type: 'text' },
    ],
    supportedEvents: [{ event: 'ON_CHANGE', description: '值變更時觸發' }],
  },
  {
    type: 'u6u-text-field',
    label: '多行輸入',
    icon: '📄',
    category: 'input',
    defaultProps: { label: '', name: '', placeholder: '輸入文字…', rows: '3' },
    propsSchema: [
      { key: 'label', label: '欄位標籤', type: 'text' },
      { key: 'name', label: '欄位名稱', type: 'text' },
      { key: 'placeholder', label: '提示文字', type: 'text' },
      { key: 'rows', label: '列數', type: 'number' },
    ],
    supportedEvents: [{ event: 'ON_CHANGE', description: '值變更時觸發' }],
  },
  {
    type: 'u6u-select',
    label: '下拉選單',
    icon: '🔽',
    category: 'input',
    defaultProps: { label: '', placeholder: '請選擇', options: '[]' },
    propsSchema: [
      { key: 'label', label: '欄位標籤', type: 'text' },
      { key: 'placeholder', label: '未選提示', type: 'text' },
      { key: 'options', label: '選項 JSON', type: 'textarea', description: '[{"value":"a","label":"A"}]' },
    ],
    supportedEvents: [{ event: 'ON_CHANGE', description: '選項變更時觸發' }],
  },
  {
    type: 'u6u-card',
    label: '智慧容器',
    icon: '🃏',
    category: 'layout',
    defaultProps: { title: '', padding: '16px' },
    propsSchema: [
      { key: 'title', label: '卡片標題', type: 'text' },
      { key: 'padding', label: '內距', type: 'text' },
    ],
    supportedEvents: [],
  },
  {
    type: 'u6u-stack',
    label: '垂直堆疊',
    icon: '📦',
    category: 'layout',
    defaultProps: { gap: '16px' },
    propsSchema: [
      { key: 'gap', label: '間距', type: 'text' },
    ],
    supportedEvents: [],
  },
  {
    type: 'u6u-row',
    label: '水平排列',
    icon: '➡️',
    category: 'layout',
    defaultProps: { gap: '8px', align: 'center', justify: 'flex-start' },
    propsSchema: [
      { key: 'gap', label: '間距', type: 'text' },
      { key: 'align', label: '對齊', type: 'text' },
      { key: 'justify', label: '排列', type: 'text' },
    ],
    supportedEvents: [],
  },
  {
    type: 'u6u-badge',
    label: '狀態標籤',
    icon: '🏷️',
    category: 'display',
    defaultProps: { label: '標籤', variant: 'default' },
    propsSchema: [
      { key: 'label', label: '顯示文字', type: 'text' },
      { key: 'variant', label: '類型', type: 'text', description: 'success|warning|error|info|default' },
    ],
    supportedEvents: [],
  },
  {
    type: 'u6u-list-item',
    label: '列表項目',
    icon: '📋',
    category: 'display',
    defaultProps: { title: '項目標題', subtitle: '' },
    propsSchema: [
      { key: 'title', label: '標題', type: 'text' },
      { key: 'subtitle', label: '副標題', type: 'text' },
    ],
    supportedEvents: [{ event: 'ON_SELECT', description: '點選時觸發' }],
  },
  {
    type: 'u6u-alert',
    label: '警告提示',
    icon: '⚠️',
    category: 'feedback',
    defaultProps: { variant: 'info', message: '提示訊息' },
    propsSchema: [
      { key: 'variant', label: '類型', type: 'text', description: 'error|success|warning|info' },
      { key: 'message', label: '訊息內容', type: 'text' },
    ],
    supportedEvents: [],
  },
  {
    type: 'u6u-spinner',
    label: '載入中',
    icon: '⏳',
    category: 'feedback',
    defaultProps: { size: 'md', color: '#8b5cf6' },
    propsSchema: [
      { key: 'size', label: '大小', type: 'text', description: 'sm|md|lg' },
      { key: 'color', label: '顏色', type: 'color' },
    ],
    supportedEvents: [],
  },
  {
    type: 'u6u-empty-state',
    label: '空狀態',
    icon: '📭',
    category: 'feedback',
    defaultProps: { icon: '📭', title: '無資料', description: '' },
    propsSchema: [
      { key: 'icon', label: '圖示', type: 'text' },
      { key: 'title', label: '標題', type: 'text' },
      { key: 'description', label: '說明', type: 'text' },
    ],
    supportedEvents: [],
  },
  {
    type: 'u6u-divider',
    label: '分隔線',
    icon: '➖',
    category: 'layout',
    defaultProps: { color: '#27272a', spacing: '8px' },
    propsSchema: [
      { key: 'color', label: '顏色', type: 'color' },
      { key: 'spacing', label: '上下間距', type: 'text' },
    ],
    supportedEvents: [],
  },
];
